# Generated by Django 5.2.5 on 2025-08-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_message_chathistory_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='lesson',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='total_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
